### ISSUE TITLE
Data still being sent to cloud

### ISSUE THREAD

**Issue by CodesInTheShell** [PathMotion/firestore-emulator-docker#1]
I have my flask app settings of environment like below,  where project-id is set to my actual project in gcloud, also set when building the docker image.

os.environ["FIRESTORE_EMULATOR_HOST"] = '0.0.0.0:8080'
os.environ["FIRESTORE_PROJECT_ID"] = 'my-project-id-in-gcloud'

navigating to 0.0.0.0:8080 via browser response is "ok". But when I add/remove data, firestore in gcloud is affected.

**Comment by maximelebastard** [comment]
We had a similar issue with our Firestore Javascript and Firestore PHP libraries. Unlike the datastore libraries, the firestore ones didn't implement the `FIRESTORE_EMULATOR_HOST` override. In consequence, they always reach the Google services instead of the emulator.

I suggest you to make sure that the Python firestore library takes `FIRESTORE_EMULATOR_HOST` into account.

Feel free to reopen the issue if the issue is actually with the emulator itself.
